"""empty message

Revision ID: 0e889bc84330
Revises: df2629b4b75e
Create Date: 2019-02-24 21:26:44.762961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e889bc84330'
down_revision = 'df2629b4b75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('assign_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'missions', 'users', ['assign_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_column('missions', 'assign_person_id')
    # ### end Alembic commands ###
