"""empty message

Revision ID: 2e5b6d4de887
Revises: 479898083cae
Create Date: 2019-02-20 23:06:49.811847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e5b6d4de887'
down_revision = '479898083cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('weekly_ibfk_2', 'weekly', type_='foreignkey')
    op.create_foreign_key(None, 'weekly', 'groups', ['group_id'], ['id'])
    op.drop_column('weekly', 'belong_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly', sa.Column('belong_to', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weekly', type_='foreignkey')
    op.create_foreign_key('weekly_ibfk_2', 'weekly', 'groups', ['belong_to'], ['id'])
    op.drop_column('weekly', 'group_id')
    # ### end Alembic commands ###
