"""empty message

Revision ID: 479898083cae
Revises: d2b2390e42d5
Create Date: 2019-02-15 16:39:40.182685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479898083cae'
down_revision = 'd2b2390e42d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relations',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    # ### end Alembic commands ###
