"""empty message

Revision ID: 4cee1991317d
Revises: 8503d046f4f4
Create Date: 2019-02-21 10:14:46.157096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cee1991317d'
down_revision = '8503d046f4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly', sa.Column('attachments', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly', 'attachments')
    # ### end Alembic commands ###
