"""empty message

Revision ID: 56d093153448
Revises: fc63e7213703
Create Date: 2019-05-09 21:44:06.129510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d093153448'
down_revision = 'fc63e7213703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_html',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_work_html', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['weekly.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_html')
    # ### end Alembic commands ###
