"""empty message

Revision ID: 5daafe261f6a
Revises: 2e5b6d4de887
Create Date: 2019-02-21 09:30:27.684850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5daafe261f6a'
down_revision = '2e5b6d4de887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('weekly_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attachment_name', mysql.VARCHAR(length=128), nullable=True),
    sa.ForeignKeyConstraint(['weekly_id'], ['weekly.id'], name='attachment_ibfk_1'),
    sa.PrimaryKeyConstraint('weekly_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
