"""empty message

Revision ID: 68cc22b6a734
Revises: 0e889bc84330
Create Date: 2019-02-25 19:17:26.593612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68cc22b6a734'
down_revision = '0e889bc84330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('missions', sa.Column('is_known', sa.Boolean(), nullable=True))
    op.add_column('missions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'timestamp')
    op.drop_column('missions', 'is_known')
    op.drop_column('missions', 'deadline')
    # ### end Alembic commands ###
