"""empty message

Revision ID: b2ee1137731d
Revises: 56d093153448
Create Date: 2019-05-09 22:19:00.792344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2ee1137731d'
down_revision = '56d093153448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly', 'finished_work_html')
    op.drop_column('weekly', 'remarks_html')
    op.drop_column('weekly', 'summary_html')
    op.drop_column('weekly', 'demands_html')
    op.drop_column('weekly', 'plan_html')
    op.add_column('weekly_html', sa.Column('demands_html', sa.Text(), nullable=True))
    op.add_column('weekly_html', sa.Column('plan_html', sa.Text(), nullable=True))
    op.add_column('weekly_html', sa.Column('remarks_html', sa.Text(), nullable=True))
    op.add_column('weekly_html', sa.Column('summary_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_html', 'summary_html')
    op.drop_column('weekly_html', 'remarks_html')
    op.drop_column('weekly_html', 'plan_html')
    op.drop_column('weekly_html', 'demands_html')
    op.add_column('weekly', sa.Column('plan_html', mysql.TEXT(), nullable=True))
    op.add_column('weekly', sa.Column('demands_html', mysql.TEXT(), nullable=True))
    op.add_column('weekly', sa.Column('summary_html', mysql.TEXT(), nullable=True))
    op.add_column('weekly', sa.Column('remarks_html', mysql.TEXT(), nullable=True))
    op.add_column('weekly', sa.Column('finished_work_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
