"""empty message

Revision ID: d2b2390e42d5
Revises: 0745b7ed265e
Create Date: 2019-02-07 15:40:00.708193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b2390e42d5'
down_revision = '0745b7ed265e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=True),
    sa.Column('group_leader', sa.Integer(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('notice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_leader'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_group_name'), 'groups', ['group_name'], unique=True)
    op.create_table('weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_work', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('demands', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('finished_work_html', sa.Text(), nullable=True),
    sa.Column('summary_html', sa.Text(), nullable=True),
    sa.Column('demands_html', sa.Text(), nullable=True),
    sa.Column('plan_html', sa.Text(), nullable=True),
    sa.Column('remarks_html', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=128), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('belong_to', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['belong_to'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_timestamp'), 'weekly', ['timestamp'], unique=False)
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    op.drop_index(op.f('ix_weekly_timestamp'), table_name='weekly')
    op.drop_table('weekly')
    op.drop_index(op.f('ix_groups_group_name'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
