"""empty message

Revision ID: d331715b8161
Revises: 4cee1991317d
Create Date: 2019-02-21 22:33:38.008111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd331715b8161'
down_revision = '4cee1991317d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly', sa.Column('subject', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly', 'subject')
    # ### end Alembic commands ###
